version: '2.1' # '2.21'

services:
  recommendation-server:
    image: celida/recommendation-server
    environment:
      GH_REPOSITORY: https://github.com/CODEX-CELIDA/celida-recommendations
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:80/fhir/version-history"]
        #start_period: 120s
        #start_interval: 5s
        interval: 5s # 60s
        timeout: 10s
        retries: 10

  execution-engine:
    build:
      context: execution-engine
      args:
        FHIR_BASE_URL: http://recommendation-server:80/fhir
        POSTGRES_HOST: 172.17.0.1
        POSTGRES_PORT: '5434'
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: yourpassword
        POSTGRES_DB: ohdsi
    depends_on:
      recommendation-server:
        condition: service_healthy
