version: '2.1' # '2.21'

services:
  recommendation-server:
    #build: recommendation-server
    image: glichtner/celida-recommendation-server
    environment:
      GH_REPOSITORY: https://github.com/CODEX-CELIDA/celida-recommendations
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:80/fhir/version-history"]
        #start_period: 120s
        #start_interval: 5s
        interval: 5s # 60s
        timeout: 10s
        retries: 10

  execution-engine:
    build:
      context: execution-engine
      args:
        FHIR_BASE_URL: http://recommendation-server:80/fhir
    depends_on:
      recommendation-server:
        condition: service_healthy
    volumes:
      - type: bind
        source: ./apply_recommendations.env
        target: /home/user/apply-recommendations/apply_recommendations.env
        read_only: true
      - type: bind
        source: ./celida.env
        target: /home/user/apply-recommendations/.env
        read_only: true
    ports:
      - "55555:55555" # trigger execution run via arbitrary POST request
